-- ESTE SCRIPT MUESTRA UNA VISTA GENERAL DE LA BASE DE DATOS, VEMOS TODAS LAS TABLAS Y SUS COLUMNAS
SELECT TABLE_NAME AS `Table`,
COLUMN_NAME AS `Column`
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'GridGuru'
ORDER BY TABLE_NAME, ORDINAL_POSITION;
